### PR TITLE
Feature/gazebo with waywise autopilot

### PR DESCRIPTION
**Pull request by r2avula**
Created a waywise_autopilot node that subscribes to odom topic and publishes waywise_vel twist messages based on waywise autopilot requests.

### CODE REVIEW

**Comment by ariamirzai** [comment]
I have tested and it works. Only issue was that keyboard input couldn't override when following a route from ControlTower.

**Review by ariamirzai — COMMENTED** [review]
I have tested and it works. Only issue was that keyboard input couldn't override when following a route from ControlTower.

**Comment by r2avula** [comment]
> I have tested and it works. Only issue was that keyboard input couldn't override when following a route from ControlTower.

It was good that you identified the issue with the keyboard. I had missed this when I tested it. This is happening because  teleop_twist_keyboard package sends twist commands only once when a keyboard key is pressed. This will be fixed with a new twist_keyboard node repalcing teleop_twist_keyboard in https://github.com/RISE-Dependable-Transport-Systems/WayWiseR/pull/30.

**Comment by rickaha** [comment]
> I have tested and it works. Only issue was that keyboard input couldn't override when following a route from ControlTower.

Keyboard can't override when following a route from ControlTower when using RCCar either, you have to stop the vehicle so it enters into manual state, in order to manually control it.

**Review by rickaha — APPROVED** [review]
Looks great, tested and work as intended.

**Pull request merged**
